#server:
 # port: 8081
  
spring:
  database: h2
  console: true
  path: /h2
  h2:    console:      enabled: true
      path: /h2-console
      settings:        trace: false
        web-allow-others: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb 
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
